-- Run this in Supabase Dashboard -> SQL Editor -> New Query -> Run
--
-- This reflects the tables/columns the app code actually reads and writes
-- (src/app/dashboard/page.js). If you're setting this up fresh, running
-- this file end to end will give you a working schema. If you already
-- have a project, compare this against what's live before running it.

-- One row per (user, unit, topic). "topic_id" is the string id generated by
-- makeId() in each unit's data module (e.g. "cardio-0-3") — scoped by
-- unit_id so two different units' topic ids can never collide.
-- "unit_id" is a plain text key matching an entry in src/lib/units.js —
-- units are defined in code, not a database table, so there's no FK here.
create table if not exists topic_progress (
  user_id uuid references auth.users(id) on delete cascade not null,
  unit_id text not null,
  topic_id text not null,
  understanding int,          -- self-rated 1-10, latest entry
  confidence int default 3,   -- 1-5, latest entry
  qcm int,                    -- latest QCM score %
  note text,
  passes int default 0,
  entries jsonb default '[]'::jsonb,   -- full log of manual entries: [{date, understanding, confidence, qcm, minutes, note, types}, ...]
  history jsonb default '[]'::jsonb,   -- full event log: [{date, action, value}, ...] — action is "pass" | "pass removed" | "assessment" | "study session"
  updated_at timestamptz default now(),
  primary key (user_id, unit_id, topic_id)
);

-- One settings row per user: theme prefs, which unit is currently open,
-- and (for now, while there's only one real unit) that unit's schedule
-- config. Once a second unit has real content, schedule fields below
-- should move to their own per-(user, unit) table — flagged here so
-- future-you doesn't forget.
create table if not exists user_settings (
  user_id uuid primary key references auth.users(id) on delete cascade,
  theme text default 'dark',                 -- 'dark' | 'solar' | 'bloom' | 'stitch' | 'minimal'
  color_mode text default 'dark',             -- 'dark' | 'light'
  display_name text,
  active_unit_id text,                       -- NULL = show the unit picker
  start_date date,
  duration_value int,
  duration_unit text default 'weeks',         -- 'weeks' | 'days'
  target_passes int default 5,
  max_modules_per_day int default 2,
  max_new_per_module_per_day int default 2,
  max_review_per_module_per_day int default 3,
  day_priority jsonb default '{"0":1,"1":1,"2":1,"3":1,"4":1,"5":1,"6":1}'::jsonb,
  schedule_data jsonb,                        -- generated/manually-edited schedule, keyed by day
  updated_at timestamptz default now()
);

-- Row Level Security: every user only ever sees their own rows
alter table topic_progress enable row level security;
alter table user_settings enable row level security;

create policy "own topic_progress" on topic_progress for all
  using (auth.uid() = user_id) with check (auth.uid() = user_id);

create policy "own settings" on user_settings for all
  using (auth.uid() = user_id) with check (auth.uid() = user_id);

